version: "3"
services:
  db:
    image: postgres:latest
    volumes:
    - .:/code
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
  app:
    build: .
    command: bash -c "sleep infinity"
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: pip install alembic
    command: alembic upgrade head
    command: python3 -m MetaButler